apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ram
  name: ram
spec:
  containers:
  - image: nginx
    name: ram
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
